live_config_reload = true

[cursor]
blink_interval = 600
unfocused_hollow = true

[env]
TERM = "alacritty"

[font]
size = 18

[hints]
alphabet = "jfkdls;ahgurieowpq"
[[hints.enabled]]
command = "xdg-open"
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^x00-x1fx7f-x9f<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"
[hints.enabled.mouse]
enabled = true
mods = "None"
[[hints.enabled]]
command = "Copy"
post_processing = false
regex = "[a-z0-9_-]+"

[hints.enabled.binding]
key = "Y"
mods = "Control|Shift"

[keyboard]
[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "K"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "L"
mods = "Control|Shift"

[mouse]
[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[[mouse.bindings]]
action = "CopySelection"
mouse = "Right"

[scrolling]
history = 100000

[window]
decorations_theme_variant = "Light"
title = "Alacritty"

[cursor.style]
blinking = "Always"

[font.bold]
family = "UbuntuMono"
style = "Bold"

[font.bold_italic]
family = "UbuntuMono"
style = "Bold Italic"

[font.italic]
family = "UbuntuMono"
style = "Italic"

[font.normal]
family = "UbuntuMono"
style = "Regular"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 1
y = 1

[colors.primary]
background = "0x103c48"
foreground = "0xadbcbc"

[colors.normal]
black = "0x184956"
red = "0xfa5750"
green = "0x75b938"
yellow = "0xdbb32d"
blue = "0x4695f7"
magenta = "0xf275be"
cyan = "0x41c7b9"
white = "0x72898f"

[colors.bright]
black = "0x2d5b69"
red = "0xff665c"
green = "0x84c747"
yellow = "0xebc13d"
blue = "0x58a3ff"
magenta = "0xff84cd"
cyan = "0x53d6c7"
white = "0xcad8d9"
