[general]
live_config_reload = true

[cursor]
blink_interval = 600
unfocused_hollow = true

[env]
TERM = "alacritty"

[font]
size = 14

[hints]
alphabet = "jfkdls;ahgurieowpq"
[[hints.enabled]]
command = "xdg-open"
hyperlinks = true
post_processing = true
persist = false
regex = '(https?://|file://|mailto:)[^\x00-\x1f\x7f-\x9f<>"\s{-}\^⟨⟩`]+'

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"
[hints.enabled.mouse]
enabled = true
mods = "None"

[keyboard]
[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "K"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "L"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Space"
mods = "Alt"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "G"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Escape"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "Left"
key = "U"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "Down"
key = "I"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "Up"
key = "O"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "Right"
key = "P"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "SemanticLeft"
key = "J"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "SemanticRight"
key = ";"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "ScrollHalfPageDown"
key = "K"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "ScrollHalfPageUp"
key = "L"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "FirstOccupied"
key = "H"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "Last"
key = "'"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "First"
key = ","
mods = "Shift"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "Last"
key = "."
mods = "Shift"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "ToggleNormalSelection"
key = "Space"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "ToggleSemanticSelection"
key = "V"
mods = "Alt"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "ToggleSemanticSelection"
key = "S"
mods = "Alt"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "ToggleLineSelection"
key = "V"
mods = "Shift"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "ToggleBlockSelection"
key = "V"
mods = "Control"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "Copy"
key = "Y"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "SearchForward"
key = "S"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "SearchForward"
key = "/"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "SearchBackward"
key = "/"
mods = "Shift"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "SearchNext"
key = "N"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "SearchPrevious"
key = "N"
mods = "Shift"
mode = "Vi|~Search"

[[keyboard.bindings]]
action = "CenterAroundViCursor"
key = "M"
mode = "Vi|~Search"

[mouse]
[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[[mouse.bindings]]
action = "CopySelection"
mouse = "Right"

[scrolling]
history = 100000

[window]
decorations_theme_variant = "Dark"
title = "Alacritty"

[cursor.style]
blinking = "Always"

[font.bold]
family = "UbuntuMono"
style = "Bold"

[font.bold_italic]
family = "UbuntuMono"
style = "Bold Italic"

[font.italic]
family = "UbuntuMono"
style = "Italic"

[font.normal]
family = "UbuntuMono"
style = "Regular"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 1
y = 1

[colors.primary]
background = "#282828"
foreground = "#ebdbb2"

[colors.normal]
black = "#282828"
red = "#cc241d"
green = "#98971a"
yellow = "#d79921"
blue = "#458588"
magenta = "#b16286"
cyan = "#689d6a"
white = "#a89984"

[colors.bright]
black = "#928374"
red = "#fb4934"
green = "#b8bb26"
yellow = "#fabd2f"
blue = "#83a598"
magenta = "#d3869b"
cyan = "#8ec07c"
white = "#ebdbb2"
